server:
  port: ${PORT:50101} #没有找到PORT时，默认为50101 PORT相当于环境变量
spring:
  application:
    name: xc-govern-center
eureka:
  server:
    enable-self-preservation: false #是否开启自我哦保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔
    instance:
      hostname: ${EUREKA_DOMAIN:eureka01}
  client:
    register-with-eureka: true #服务注册，是否将自己注册到Enreka中
    fetch-registry: true #服务发现，是否荣Eureka中获取注册信息
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
