server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      host: localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: ${EUREKA_SERVER:http://localhost:50102/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
